spring.datasource.url=jdbc:postgresql://localhost:5432/kamboost
spring.datasource.username=postgres
spring.datasource.password=131312

spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always

api.security.token.secret=${JWT_SECRET:my-secret-key}